### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by zakjan** [MODLanguage/antlr4-ruby-runtime#9]
Parsing using Ruby runtime takes significantly longer than other runtimes. It seems that Ruby runtime performs something inefficient by mistake, is it possible? Or is the slowness related to Ruby interpreter?

The grammar is moderately complex (191 parser rules, 132 lexer rules), available [here](https://github.com/lutaml/express-grammar/blob/master/Express.g4). Some input files are available online.

See the measurements (avg of 5 runs) below:

274 lines input file available [here](https://ap238.org/SMRL_v8_final/data/resources/action_schema/action_schema.exp)

Java - 0.391s
JS - 0.453s
Ruby - 4.722s

1314 lines input file which is structurally the same as the first file, just with additional comments (EmbeddedRemark and LineRemark lexer rules)

Java - 0.395s
JS - 0.444s
Ruby - 6.205s

14742 lines input file available [here](http://ap238.org/ap238e1/wg3n2097_ap238.exp)

Java - 2.393s
JS - 3.945s
Ruby - 34m55s (1 run)

27754 lines input file

Java - 1.682s
JS - 2.916s
Ruby - 2m49s

**Comment by twalmsley** [comment]
Hi Jan,

Yes we noticed poor performance with some grammars and/or larger input files - ours are currently quite small. You might like to see [this](https://github.com/camertron/antlr4-native-rb) repo which will produce Ruby native parsers  'for (almost) any ANTLR4 grammar', which we intend to use for our parser at some point. 

We were able to improve performance considerably by making small changes to the lexer and parser rules which reduced the amount of lookahead needed when parsing our files, but I doubt that will be a solution for you since `EXPRESS` is a defined standard.

I was unable to find a bug in the runtime when I did some performance testing last year, but I could easily have missed something since the runtime is quite complex. Once possibility is that Ruby creates objects for everything rather than supporting primitive types, which will therefore use more memory and reduce performance.

Please comment here if the native Ruby parser solves your performance problem.

Tony

**Comment by ronaldtse** [comment]
@twalmsley thank you for the great tip! It might be possible for us to tweak the grammar slightly -- do you have any advice on how to reduce the amount of lookahead needed? 

More importantly, @zakjan and I originally planned to go native if the performance couldn't be improved, but your advice on [antlr4-native-rb](https://github.com/camertron/antlr4-native-rb) will save us tons of time...

**Comment by zakjan** [comment]
I doubt that trying to simplify a complex grammar would help significantly.

This note in [antlr-gemerator](https://github.com/camertron/antlr-gemerator) confirms that it is a more general issue. Also, it answers why your ANTLR4 Ruby fork wasn't merged upstream yet.

> A couple of attempts have been made over the years to add a Ruby target to ANTLR, including this excellent one from @twalmsley. Unfortunately none of these attempts have been merged into ANTLR proper yet.
> The real problem with a Ruby target however is execution speed. The runtime linked above runs ~80% slower than the equivalent Java-based Python parser I'm working on.

Indeed after seeing the performance, our first thought was to go with C++ FFI. Thanks for pointing us to the repo, we'll try it out!

**Comment by twalmsley** [comment]
Good luck with the gemerator - we will probably deprecate this runtime at some point in favour of Camertron's solution, and it would be good to get some feedback about how you get on if you have time. Its a shame that the pure Ruby runtime isn't viable, but I guess its possible that some future bug fix will mitigate the problem at some point.

Just for info: Our Ruby parser is one of several versions in different languages, so generally we use our Java version and plan to update the Ruby version to Camertron's solution in future. Our original grammar was badly defined since it included white-space tokens in rules (leading to too many unnecessary tokens) and allowed white-space in STRING tokens. I think the STRING tokens were the main performance problem for us, partly because our language is loose where STRING delimiters are concerned - they're not always necessary (in order to save space), so the parser was searching to the end of the file looking for the end of every STRING. Grammars that use delimiters 'properly' shouldn't have this problem.

**Comment by zakjan** [comment]
Thanks for the insight! I'm closing this because bad performance is most likely caused by the interpreter.
